# Generated by Django 3.2.8 on 2021-10-28 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_book_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='issue_date',
            field=models.DateField(verbose_name='Дата выпуска'),
        ),
    ]
