# Generated by Django 3.2.8 on 2021-10-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211028_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='issue_date',
            field=models.DateField(help_text='Формат: дд.мм.год', verbose_name='Дата выпуска'),
        ),
    ]
