# Generated by Django 3.2.8 on 2021-10-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20211029_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Для того чтобы выбрать несколько жанров, зажмите клавишу ctrl', to='mainapp.Genre', verbose_name='Жанр'),
        ),
    ]
